---
- name: Add Upstart script
  copy: src=ansible/files/startup/chargingsystem.conf dest=/etc/init/chargingsystem.conf owner=root group=root mode=0644
  sudo: yes
  tags:
    - api
    - config

- name: Build assembly package
  command: java -jar /opt/sbt/sbt.jar clean assembly
  args:
    chdir: /vagrant
  tags:
    - app

- name: Start charging-system-api service if its not running
  service: name=charging-system-api state=started enabled=yes
  sudo: yes
  tags:
    - api