---
- name: Add Upstart script
  copy: src=ansible/files/startup/newmotion.conf dest=/etc/init/newmotion.conf owner=root group=root mode=0644
  sudo: yes
  tags:
    - api
    - config

- name: Build assembly package
  command: java -jar /opt/sbt/sbt.jar clean assembly
  args:
    chdir: /vagrant
  tags:
    - app

- name: Start newmotion service if its not running
  service: name=newmotion state=started enabled=yes
  sudo: yes
  tags:
    - api